### ISSUE TITLE
Some modules doesn't install correctly

### ISSUE THREAD

**Issue by calapout** [DasWolke/rem-v2#116]
When you install the bot on local, it doesn't install all the module and make the script crash when launch.
https://images.discordapp.net/.eJwlyFEOgyAMANC7cADqqKydtyFI0EwpoTV-LLv7PvY-38dd43CL28y6LgDrrlnG6tVkpFp8FalHSX1Xn-WEZJbydpZmCoEiMk4xvBgJpwfxv2bESPyMhBxmuNq7yd18b9V9fwlAIu8.d0O4VQVzwlhHFkEwnP9q2dSbWH0?width=1168&height=657

**Comment by DasWolke** [comment]
As a Temp Fix do `npm install uws --save` and remove the canvas.js which is in commands\moderation\canvas.js, delete the dist folder and run `npm run build` again

**Comment by DasWolke** [comment]
I will probably switch the dependency to ws as the errors are a lot more comprehensive and uws is a bit buggy with node
