### ISSUE TITLE
Throwing instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by MewRage** [DasWolke/rem-v2#118]
When running Rem locally, the scripts launches without crashing, but the picture attached shows the errors. 
![image](https://cloud.githubusercontent.com/assets/8375437/22529363/280941da-e8a5-11e6-9414-3ed37be7f604.png)

**Comment by DasWolke** [comment]
Hey there, that is a missing arg in the config, add "ws_port":port to the main.json file. I did not update the readme yet to include it.
