### ISSUE TITLE
When trying run on local workers are just crushing.

### ISSUE THREAD

**Issue by iSm1le** [DasWolke/rem-v2#119]
When you do a clean install on win 10 x64 you got just a "worker died" message.
And manually installed uws, because it doesn't installing automatically as said in [#116](https://github.com/DasWolke/rem-v2/issues/116)
![1](https://cloud.githubusercontent.com/assets/12123860/22620650/f57d9a92-eb18-11e6-9b4a-49025119d3f1.PNG)

**Comment by DasWolke** [comment]
Currently working on refactoring some stuff. I will reference this once I fixed it.

**Comment by DasWolke** [comment]
Alright should be cool now. I would close this. Reopen it if needed.
