### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by wamuzu** [DasWolke/rem-v2#124]
While a song from Youtube is being played, it will randomly cut it off and give the ECONNRESET error as displayed here:

![](http://i.imgur.com/5b2GNbC.png)

This happens every single time Music is being played.

**Comment by DasWolke** [comment]
This just happens when the source, where the music is got from closes the connection. Therefore it just happens and could be caused by network bugs on your side. This is not caused by rem.
